ESX = nil

TriggerEvent('esx:getSharedObject', function(obj) ESX = obj end)



ESX.RegisterUsableItem('bread', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)

	xPlayer.removeInventoryItem('bread', 1)

	TriggerClientEvent('esx_status:add', source, 'hunger', 150000)
	TriggerClientEvent('esx_basicneeds:onEat', source)
	TriggerClientEvent('esx:showNotification', source, ('vous avez consommer ~y~1x~s~ ~b~Pain~s~'))
end)
ESX.RegisterUsableItem('hamburger', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('hamburger', 1)
	TriggerClientEvent('esx_status:add', source, 'hunger', 250000)
	TriggerClientEvent('esx_basicneeds:onEat', source)
	TriggerClientEvent('esx:showNotification', source, ('vous avez consommer ~y~1x~s~ ~b~Hamburger~s~'))
end)
ESX.RegisterUsableItem('saucisson', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('saucisson', 1)
	TriggerClientEvent('esx_status:add', source, 'hunger', 100000)
	TriggerClientEvent('esx_basicneeds:onEat', source)
	TriggerClientEvent('esx:showNotification', source, ('vous avez consommer ~y~1x~s~ ~b~Saucisson~s~'))
end)

ESX.RegisterUsableItem('donut', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('donut', 1)
	TriggerClientEvent('esx_status:add', source, 'hunger', 150000)
	TriggerClientEvent('esx_basicneeds:onEat', source)
	TriggerClientEvent('esx:showNotification', source, ('vous avez consommer ~y~1x~s~ ~b~Donut~s~'))
end)

ESX.RegisterUsableItem('donuts', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('donuts', 1)
	TriggerClientEvent('esx_status:add', source, 'hunger', 450000)
	TriggerClientEvent('esx_basicneeds:onEat', source)
	TriggerClientEvent('esx:showNotification', source, ('vous avez consommer ~y~1x~s~ ~b~Donut au Cacahuète~s~'))
end)

ESX.RegisterUsableItem('tacos', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('tacos', 1)
	TriggerClientEvent('esx_status:add', source, 'hunger', 400000)
	TriggerClientEvent('esx_basicneeds:onEat', source)
	TriggerClientEvent('esx:showNotification', source, ('vous avez consommer ~y~1x~s~ ~b~Tacos~s~'))
end)

ESX.RegisterUsableItem('tomate', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('tomate', 1)
	TriggerClientEvent('esx_status:add', source, 'hunger', 25000)
	TriggerClientEvent('esx_basicneeds:onEat', source)
	TriggerClientEvent('esx:showNotification', source, ('vous avez consommer ~y~1x~s~ ~b~Tomate~s~'))
end)

ESX.RegisterUsableItem('salade', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('salade', 1)
	TriggerClientEvent('esx_status:add', source, 'hunger', 35000)
	TriggerClientEvent('esx_basicneeds:onEat', source)
	TriggerClientEvent('esx:showNotification', source, ('vous avez consommer ~y~1x~s~ ~b~Salade~s~'))
end)

ESX.RegisterUsableItem('salademixte', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('salademixte', 1)
	TriggerClientEvent('esx_status:add', source, 'hunger', 250000)
	TriggerClientEvent('esx_basicneeds:onEat', source)
	TriggerClientEvent('esx:showNotification', source, ('vous avez consommer ~y~1x~s~ ~b~Mixe de salade~s~'))
end)

ESX.RegisterUsableItem('sandwichviande', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('sandwichviande', 1)
	TriggerClientEvent('esx_status:add', source, 'hunger', 850000)
	TriggerClientEvent('esx_basicneeds:onEat2', source)
	TriggerClientEvent('esx:showNotification', source, ('vous avez consommer ~y~1x~s~ ~b~Sandwich au viande~s~'))
end)

ESX.RegisterUsableItem('kebab', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('kebab', 1)
	TriggerClientEvent('esx_status:add', source, 'hunger', 500000)
	TriggerClientEvent('esx_basicneeds:onEat', source)
	TriggerClientEvent('esx:showNotification', source, ('vous avez consommer ~y~1x~s~ ~b~Kebab~s~'))
end)
ESX.RegisterUsableItem('sandwich', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('sandwich', 1)
	TriggerClientEvent('esx_status:add', source, 'hunger', 450000)
	TriggerClientEvent('esx_basicneeds:onEat2', source)
	TriggerClientEvent('esx:showNotification', source, ('vous avez consommer ~y~1x~s~ ~b~Sandwich~s~'))
end)
ESX.RegisterUsableItem('burritos', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('burritos', 1)
	TriggerClientEvent('esx_status:add', source, 'hunger', 200000)
	TriggerClientEvent('esx_basicneeds:onEat', source)
	TriggerClientEvent('esx:showNotification', source, ('vous avez consommer ~y~1x~s~ ~b~Burritos~s~'))
end)

ESX.RegisterUsableItem('pomme', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('pomme', 1)
	TriggerClientEvent('esx_status:add', source, 'hunger', 50000)
	TriggerClientEvent('esx_basicneeds:onEat', source)
	TriggerClientEvent('esx:showNotification', source, ('vous avez consommer ~y~1x~s~ ~b~Pomme~s~'))
end)

ESX.RegisterUsableItem('saladefruit', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('saladefruit', 1)
	TriggerClientEvent('esx_status:add', source, 'hunger', 250000)
	TriggerClientEvent('esx_basicneeds:onEat', source)
	TriggerClientEvent('esx:showNotification', source, ('vous avez consommer ~y~1x~s~ ~b~Salle de fruit~s~'))
end)

ESX.RegisterUsableItem('pommeterre', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('pommeterre', 1)
	TriggerClientEvent('esx_status:add', source, 'hunger', 50000)
	TriggerClientEvent('esx_basicneeds:onEat', source)
	TriggerClientEvent('esx:showNotification', source, ('vous avez consommer ~y~1x~s~ ~b~Pomme de terre~s~'))
end)
ESX.RegisterUsableItem('cornetfrite', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('cornetfrite', 1)
	TriggerClientEvent('esx_status:add', source, 'hunger', 250000)
	TriggerClientEvent('esx_basicneeds:onEat', source)
	TriggerClientEvent('esx:showNotification', source, ('vous avez consommer ~y~1x~s~ ~b~Cornet de frite~s~'))
end)


ESX.RegisterUsableItem('pizza', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('pizza', 1)
	TriggerClientEvent('esx_status:add', source, 'hunger', 300000)
	TriggerClientEvent('esx_basicneeds:onEat', source)
	TriggerClientEvent('esx:showNotification', source, ('vous avez consommer ~y~1x~s~ ~b~Pizza~s~'))
end)

ESX.RegisterUsableItem('cacahuete', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('cacahuete', 1)
	TriggerClientEvent('esx_status:add', source, 'hunger', 180000)
	TriggerClientEvent('esx_basicneeds:onEat', source)
	TriggerClientEvent('esx:showNotification', source, ('vous avez consommer ~y~1x~s~ ~b~Cacahuète~s~'))
end)

ESX.RegisterUsableItem('bolcacahuete', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('bolcacahuete', 1)
	TriggerClientEvent('esx_status:add', source, 'hunger', 300000)
	TriggerClientEvent('esx_basicneeds:onEat', source)
	TriggerClientEvent('esx:showNotification', source, ('vous avez consommer ~y~1x~s~ ~b~Bol de Cacahuète~s~'))
end)

ESX.RegisterUsableItem('chickenburger', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('chickenburger', 1)
	TriggerClientEvent('esx_status:add', source, 'hunger', 500000)
	TriggerClientEvent('esx_basicneeds:onEat', source)
	TriggerClientEvent('esx:showNotification', source, ('vous avez consommer ~y~1x~s~ ~b~Chicken Burger~s~'))
end)


ESX.RegisterUsableItem('fishburger', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('fishburger', 1)
	TriggerClientEvent('esx_status:add', source, 'hunger', 450000)
	TriggerClientEvent('esx_basicneeds:onEat', source)
	TriggerClientEvent('esx:showNotification', source, ('vous avez consommer ~y~1x~s~ ~b~Chicken Burger~s~'))
end)

ESX.RegisterUsableItem('soupetomate', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('soupetomate', 1)
	TriggerClientEvent('esx_status:add', source, 'hunger', 350000)
	TriggerClientEvent('esx_status:add', source, 'thirst', 350000)
	TriggerClientEvent('esx_basicneeds:onEat', source)
	TriggerClientEvent('esx:showNotification', source, ('vous avez consommer ~y~1x~s~ ~b~Soupe à la Tomate~s~'))
end)

ESX.RegisterUsableItem('saladecesar', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('saladecesar', 1)
	TriggerClientEvent('esx_status:add', source, 'hunger', 300000)
	TriggerClientEvent('esx_basicneeds:onEat', source)
	TriggerClientEvent('esx:showNotification', source, ('vous avez consommer ~y~1x~s~ ~b~Bol de Salade César~s~'))
end)

ESX.RegisterUsableItem('delicious', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('delicious', 1)
	TriggerClientEvent('esx_status:add', source, 'hunger', 450000)
	TriggerClientEvent('esx_basicneeds:onEat', source)
	TriggerClientEvent('esx:showNotification', source, ('vous avez consommer ~y~1x~s~ ~b~Delicious Sandwich~s~'))
end)

ESX.RegisterUsableItem('venetoast', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('delicious', 1)
	TriggerClientEvent('esx_status:add', source, 'hunger', 150000)
	TriggerClientEvent('esx_basicneeds:onEat', source)
	TriggerClientEvent('esx:showNotification', source, ('vous avez consommer ~y~1x~s~ ~b~Venetoast~s~'))
end)


ESX.RegisterUsableItem('water', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('water', 1)
	TriggerClientEvent('esx_status:add', source, 'thirst', 180000)
	TriggerClientEvent('esx_basicneeds:onDrink', source)
	TriggerClientEvent('esx:showNotification', source, ('vous avez consommer ~y~1x~s~ ~b~Bouteille d\'eau~s~'))
end)

ESX.RegisterUsableItem('oasis', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('oasis', 1)
	TriggerClientEvent('esx_status:add', source, 'thirst', 250000)
	TriggerClientEvent('esx_basicneeds:onDrink', source)
	TriggerClientEvent('esx:showNotification', source, ('vous avez consommer ~y~1x~s~ ~b~Bouteille d\'Oasis~s~'))
end)
ESX.RegisterUsableItem('monster', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('monster', 1)
	TriggerClientEvent('esx_status:add', source, 'thirst', 350000)
	TriggerClientEvent('esx_basicneeds:onDrink', source)
--	TriggerClientEvent('boost:Monster', source)
	TriggerClientEvent('esx:showNotification', source, ('vous avez consommer ~y~1x~s~ ~b~Bouteille de Monster~s~'))
end)
ESX.RegisterUsableItem('redbull', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('redbull', 1)
	TriggerClientEvent('esx_status:add', source, 'thirst', 360000)
	TriggerClientEvent('esx_basicneeds:onDrink', source)
--	TriggerClientEvent('boost:Monster', source)
	TriggerClientEvent('esx:showNotification', source, ('vous avez consommer ~y~1x~s~ ~b~Bouteille de Redbull~s~'))
end)
ESX.RegisterUsableItem('cocacola', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('cocacola', 1)
	TriggerClientEvent('esx_status:add', source, 'thirst', 270000)
	TriggerClientEvent('esx_basicneeds:onDrink', source)
	TriggerClientEvent('esx:showNotification', source, ('vous avez consommer ~y~1x~s~ ~b~Bouteille de Coca Cola~s~'))
end)

ESX.RegisterUsableItem('cafe', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('cafe', 1)
	TriggerClientEvent('esx_status:add', source, 'thirst', 290000)
	TriggerClientEvent('esx_basicneeds:onDrink', source)
	TriggerClientEvent('esx:showNotification', source, ('vous avez consommer ~y~1x~s~ Café~s~'))
end)

ESX.RegisterUsableItem('desperados', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('desperados', 1)
	TriggerClientEvent('esx_status:add', source, 'drug', 220000)
	TriggerClientEvent('esx_basicneeds:onDrink', source)
	TriggerClientEvent('esx:showNotification', source, ('vous avez consommer ~y~1x~s~ ~b~Bouteille de Desperados~s~'))
end)
ESX.RegisterUsableItem('biere', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('biere', 1)
	TriggerClientEvent('esx_status:add', source, 'drug', 120000)
	TriggerClientEvent('esx_basicneeds:onDrink', source)
	TriggerClientEvent('esx:showNotification', source, ('vous avez consommer ~y~1x~s~ ~b~Bouteille de Bière~s~'))
end)
ESX.RegisterUsableItem('jager', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('jager', 1)
	TriggerClientEvent('esx_status:add', source, 'drug', 280000)
	TriggerClientEvent('esx_basicneeds:onDrink', source)
	TriggerClientEvent('esx:showNotification', source, ('vous avez consommer ~y~1x~s~ ~b~Bouteille de Jager~s~'))
end)
ESX.RegisterUsableItem('jackdaniel', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('jackdaniel', 1)
	TriggerClientEvent('esx_status:add', source, 'drug', 300000)
	TriggerClientEvent('esx_basicneeds:onDrink', source)
	TriggerClientEvent('esx:showNotification', source, ('vous avez consommer ~y~1x~s~ ~b~Bouteille de Jack Daniel\'s~s~'))
end)


ESX.RegisterUsableItem('rhum', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('rhum', 1)
	TriggerClientEvent('esx_status:add', source, 'thirst', 270000)
	TriggerClientEvent('esx_basicneeds:onDrink', source)
	TriggerClientEvent('esx:showNotification', source, ('vous avez consommer ~y~1x~s~ ~b~ Rhum~s~'))
end)


ESX.RegisterUsableItem('mojitos', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('mojitos', 1)
	TriggerClientEvent('esx_status:add', source, 'thirst', 400000)
	TriggerClientEvent('esx_basicneeds:onDrink', source)
	TriggerClientEvent('esx:showNotification', source, ('vous avez consommer ~y~1x~s~ ~b~ Mojitos~s~'))
end)

ESX.RegisterUsableItem('unicorncocktail', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('unicorncocktail', 1)
	TriggerClientEvent('esx_status:add', source, 'thirst', 300000)
	TriggerClientEvent('esx_status:add', source, 'hunger', 300000)
	TriggerClientEvent('esx_basicneeds:onDrink2', source)
	TriggerClientEvent('esx:showNotification', source, ('vous avez consommer ~y~1x~s~ ~b~ Tikikilala~s~'))
end)

ESX.RegisterUsableItem('venetiecocktail', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('venetiecocktail', 1)
	TriggerClientEvent('esx_status:add', source, 'drug', 350000)
	TriggerClientEvent('esx_status:add', source, 'thirst', 100000)
	TriggerClientEvent('esx_status:add', source, 'hunger', 100000)
	TriggerClientEvent('esx_basicneeds:onDrink2', source)
	TriggerClientEvent('esx:showNotification', source, ('vous avez consommer ~y~1x~s~ ~b~ Le Veneties Cocktail~s~'))
end)


ESX.RegisterUsableItem('venetiesboomboom', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('venetiesboomboom', 1)
	TriggerClientEvent('esx_status:add', source, 'drug', 550000)
	TriggerClientEvent('esx_basicneeds:onDrink2', source)
	TriggerClientEvent('esx:showNotification', source, ('vous avez consommer ~y~1x~s~ ~b~ Vénétie\'s Boom Boom~s~'))
end)

ESX.RegisterUsableItem('rugissementlion', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('rugissementlion', 1)
	TriggerClientEvent('esx_status:add', source, 'thirst', 700000)
	TriggerClientEvent('esx_status:add', source, 'hunger', 300000)
	TriggerClientEvent('esx_basicneeds:onDrink2', source)
	TriggerClientEvent('esx:showNotification', source, ('vous avez consommer ~y~1x~s~ ~b~ Le Rugissement du Lion~s~'))
end)

ESX.RegisterUsableItem('pissedelicorne', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('pissedelicorne', 1)
	TriggerClientEvent('esx_status:add', source, 'drug', 250000)
	TriggerClientEvent('esx_basicneeds:onDrink', source)
	TriggerClientEvent('boost:pisse', source)
	TriggerClientEvent('esx:showNotification', source, ('vous avez consommer ~y~1x~s~ ~b~Bouteille de Molotov~s~'))
end)

ESX.RegisterUsableItem('absynthe', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('absynthe', 1)
	TriggerClientEvent('esx_status:add', source, 'drug', 450000)
	TriggerClientEvent('esx_basicneeds:onDrink', source)
	TriggerClientEvent('esx:showNotification', source, ('vous avez consommer ~y~1x~s~ ~b~Bouteille d\'Absynthe~s~'))
end)


ESX.RegisterUsableItem('jackcharlie', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('jackcharlie', 1)
	TriggerClientEvent('esx_status:add', source, 'drug', 300000)
	TriggerClientEvent('esx_basicneeds:onDrink', source)
	TriggerClientEvent('esx:showNotification', source, ('vous avez consommer ~y~1x~s~ ~b~Bouteille de Jack Charlie\'s~s~'))
end)

ESX.RegisterUsableItem('vodka', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('vodka', 1)
	TriggerClientEvent('esx_status:add', source, 'drug', 300000)
	TriggerClientEvent('esx_basicneeds:onDrink', source)
	TriggerClientEvent('esx:showNotification', source, ('vous avez consommer ~y~1x~s~ ~b~Bouteille de Vodka~s~'))
end)
ESX.RegisterUsableItem('tquilafrappee', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('tquilafrappee', 1)
	TriggerClientEvent('esx_status:add', source, 'drug', 300000)
	TriggerClientEvent('esx_basicneeds:onDrink', source)
	TriggerClientEvent('esx:showNotification', source, ('vous avez consommer ~y~1x~s~ ~b~Bouteille de Téquila frappée~s~'))
end)

ESX.RegisterUsableItem('leffe', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('leffe', 1)
	TriggerClientEvent('esx_status:add', source, 'drug', 200000)
	TriggerClientEvent('esx_basicneeds:onDrink', source)
	TriggerClientEvent('esx:showNotification', source, ('vous avez consommer ~y~1x~s~ ~b~Bouteille de Leffe~s~'))
end)

ESX.RegisterUsableItem('milk', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('milk', 1)
	TriggerClientEvent('esx_status:add', source, 'drug', -100000)
	TriggerClientEvent('esx_basicneeds:onDrink', source)
	TriggerClientEvent('esx:showNotification', source, ('Vous avez utilisé ~g~1x Lait'))
end)




ESX.RegisterUsableItem('cartoncafe', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('cartoncafe', 1)
	xPlayer.addInventoryItem('cafe', 50)
	TriggerClientEvent('esx:showNotification', source, ('Vous avez ouvert votre ~g~Paquet de cafe'))
end)
ESX.RegisterUsableItem('cartoncocacola', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('cartoncocacola', 1)
	xPlayer.addInventoryItem('cocacola', 50)
	TriggerClientEvent('esx:showNotification', source, ('Vous avez ouvert votre ~g~Paquet de Coca Cola'))
end)
ESX.RegisterUsableItem('cartondonut', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('cartondonut', 1)
	xPlayer.addInventoryItem('donut', 50)
	TriggerClientEvent('esx:showNotification', source, ('Vous avez ouvert votre ~g~Paquet de donut'))
end)
ESX.RegisterUsableItem('cartonhamburger', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('cartonhamburger', 1)
	xPlayer.addInventoryItem('hamburger', 50)
	TriggerClientEvent('esx:showNotification', source, ('Vous avez ouvert votre ~g~Paquet de Hamburger'))
end)
ESX.RegisterUsableItem('cartonkebab', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('cartonkebab', 1)
	xPlayer.addInventoryItem('kebab', 50)
	TriggerClientEvent('esx:showNotification', source, ('Vous avez ouvert votre ~g~Paquet de Kebab'))
end)
ESX.RegisterUsableItem('cartonmilk', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('cartonmilk', 1)
	xPlayer.addInventoryItem('milk', 50)
	TriggerClientEvent('esx:showNotification', source, ('Vous avez ouvert votre ~g~Paquet de Lait'))
end)
ESX.RegisterUsableItem('cartonmonster', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('cartonmonster', 1)
	xPlayer.addInventoryItem('monster', 50)
	TriggerClientEvent('esx:showNotification', source, ('Vous avez ouvert votre ~g~Paquet de Monster'))
end)
ESX.RegisterUsableItem('cartonoasis', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('cartonoasis', 1)
	xPlayer.addInventoryItem('oasis', 50)
	TriggerClientEvent('esx:showNotification', source, ('Vous avez ouvert votre ~g~Paquet de Oasis'))
end)
ESX.RegisterUsableItem('cartonredbull', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('cartonredbull', 1)
	xPlayer.addInventoryItem('redbull', 50)
	TriggerClientEvent('esx:showNotification', source, ('Vous avez ouvert votre ~g~Paquet de Redbull'))
end)
ESX.RegisterUsableItem('cartonsaucisson', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('cartonsaucisson', 1)
	xPlayer.addInventoryItem('saucisson', 50)
	TriggerClientEvent('esx:showNotification', source, ('Vous avez ouvert votre ~g~Paquet de Saucisson'))
end)
ESX.RegisterUsableItem('cartontacos', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('cartontacos', 1)
	xPlayer.addInventoryItem('tacos', 50)
	TriggerClientEvent('esx:showNotification', source, ('Vous avez ouvert votre ~g~Paquet de Tacos'))
end)
ESX.RegisterUsableItem('cartonwater', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('cartonwater', 1)
	xPlayer.addInventoryItem('water', 50)
	TriggerClientEvent('esx:showNotification', source, ('Vous avez ouvert votre ~g~Paquet de Bouteille d\'eau'))
end)
ESX.RegisterUsableItem('cartoncontract', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('cartoncontract', 1)
	xPlayer.addInventoryItem('contract', 50)
	TriggerClientEvent('esx:showNotification', source, ('Vous avez ouvert votre ~g~Paquet de Contrat'))
end)
ESX.RegisterUsableItem('cartonlighter', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('cartonlighter', 1)
	xPlayer.addInventoryItem('lighter', 50)
	TriggerClientEvent('esx:showNotification', source, ('Vous avez ouvert votre ~g~Paquet de Briquet'))
end)
ESX.RegisterUsableItem('cartonphone', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('cartonphone', 1)
	xPlayer.addInventoryItem('phone', 50)
	TriggerClientEvent('esx:showNotification', source, ('Vous avez ouvert votre ~g~Paquet de Téléphone'))
end)
ESX.RegisterUsableItem('cartonburritos', function(source) 
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('cartonburritos', 1)
	xPlayer.addInventoryItem('burritos', 50)
	TriggerClientEvent('esx:showNotification', source, ('Vous avez ouvert votre ~g~Paquet de Burritos'))
end)






ESX.RegisterUsableItem('cartonfixkit', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	TriggerClientEvent('carton:cartonfixkit', source)
end)
RegisterServerEvent("carton:cartonfixkitopen")
AddEventHandler("carton:cartonfixkitopen", function()
     local xPlayer        = ESX.GetPlayerFromId(source)
     xPlayer.removeInventoryItem('cartonfixkit', 1)
     xPlayer.addInventoryItem('fixkit', 50)
end)
--
ESX.RegisterUsableItem('cartonrevivekit', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	TriggerClientEvent('carton:cartonrevivekit', source)
end)
RegisterServerEvent("carton:cartonrevivekitopen")
AddEventHandler("carton:cartonrevivekitopen", function()
	local _source = source
     local xPlayer        = ESX.GetPlayerFromId(source)
     xPlayer.removeInventoryItem('cartonrevivekit', 1)
     xPlayer.addInventoryItem('revivekit', 25)
end)

ESX.RegisterUsableItem('cartonmedikit', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	TriggerClientEvent('carton:cartonmedikit', source)
end)
RegisterServerEvent("carton:cartonmedikitopen")
AddEventHandler("carton:cartonmedikitopen", function()
	local _source = source
     local xPlayer        = ESX.GetPlayerFromId(source)
     xPlayer.removeInventoryItem('cartonmedikit', 1)
     xPlayer.addInventoryItem('medikit', 50)
end)
--
ESX.RegisterUsableItem('cartonbandage', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	TriggerClientEvent('carton:cartonbandage', source)
end)
RegisterServerEvent("carton:cartonbandageopen")
AddEventHandler("carton:cartonbandageopen", function()
	local _source = source
     local xPlayer        = ESX.GetPlayerFromId(source)
     xPlayer.removeInventoryItem('cartonbandage', 1)
     xPlayer.addInventoryItem('bandage', 50)
end)

--
ESX.RegisterUsableItem('cartonjackcharlie', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	TriggerClientEvent('carton:cartonjackcharlie', source)
end)
RegisterServerEvent("carton:cartonjackcharlieopen")
AddEventHandler("carton:cartonjackcharlieopen", function()
	local _source = source
     local xPlayer        = ESX.GetPlayerFromId(source)
     xPlayer.removeInventoryItem('cartonjackcharlie', 1)
     xPlayer.addInventoryItem('jackcharlie', 50)
end)
--
ESX.RegisterUsableItem('cartonpissedelicorne', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	TriggerClientEvent('carton:cartonpissedelicorne', source)
end)
RegisterServerEvent("carton:cartonpissedelicorneopen")
AddEventHandler("carton:cartonpissedelicorneopen", function()
	local _source = source
     local xPlayer        = ESX.GetPlayerFromId(source)
     xPlayer.removeInventoryItem('cartonpissedelicorne', 1)
     xPlayer.addInventoryItem('pissedelicorne', 50)
end)
--
ESX.RegisterUsableItem('cartonabsynthe', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	TriggerClientEvent('carton:cartonabsynthe', source)
end)
RegisterServerEvent("carton:cartonabsyntheopen")
AddEventHandler("carton:cartonabsyntheopen", function()
	local _source = source
     local xPlayer        = ESX.GetPlayerFromId(source)
     xPlayer.removeInventoryItem('cartonabsynthe', 1)
     xPlayer.addInventoryItem('absynthe', 50)
end)
--
ESX.RegisterUsableItem('cartonbiere', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	TriggerClientEvent('carton:cartonbiere', source)
end)
RegisterServerEvent("carton:cartonbiereopen")
AddEventHandler("carton:cartonbiereopen", function()
	local _source = source
     local xPlayer        = ESX.GetPlayerFromId(source)
     xPlayer.removeInventoryItem('cartonbiere', 1)
     xPlayer.addInventoryItem('biere', 50)
end)
--
ESX.RegisterUsableItem('cartondesperados', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	TriggerClientEvent('carton:cartondesperados', source)
end)
RegisterServerEvent("carton:cartondesperadosopen")
AddEventHandler("carton:cartondesperadosopen", function()
	local _source = source
     local xPlayer        = ESX.GetPlayerFromId(source)
     xPlayer.removeInventoryItem('cartondesperados', 1)
     xPlayer.addInventoryItem('desperados', 50)
end)
--
ESX.RegisterUsableItem('cartonjackdaniel', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	TriggerClientEvent('carton:cartonjackdaniel', source)
end)
RegisterServerEvent("carton:cartondesperadosopen")
AddEventHandler("carton:cartondesperadosopen", function()
	local _source = source
     local xPlayer        = ESX.GetPlayerFromId(source)
     xPlayer.removeInventoryItem('cartonjackdaniel', 1)
     xPlayer.addInventoryItem('jackdaniel', 50)
end)
--
ESX.RegisterUsableItem('cartonjager', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	TriggerClientEvent('carton:cartonjager', source)
end)
RegisterServerEvent("carton:cartonjageropen")
AddEventHandler("carton:cartonjageropen", function(source)
     local xPlayer        = ESX.GetPlayerFromId(source)
     xPlayer.removeInventoryItem('cartonjager', 1)
     xPlayer.addInventoryItem('jager', 50)
end)
--
ESX.RegisterUsableItem('cartonleffe', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	TriggerClientEvent('carton:cartonleffe', source)
end)
RegisterServerEvent("carton:cartonleffeopen")
AddEventHandler("carton:cartonleffeopen", function()
	local _source = source
     local xPlayer        = ESX.GetPlayerFromId(source)
     xPlayer.removeInventoryItem('cartonleffe', 1)
     xPlayer.addInventoryItem('leffe', 50)
end)
--
ESX.RegisterUsableItem('cartonmojitos', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	TriggerClientEvent('carton:cartonmojitos', source)
end)
RegisterServerEvent("carton:cartonmojitosopen")
AddEventHandler("carton:cartonmojitosopen", function()
	local _source = source
     local xPlayer        = ESX.GetPlayerFromId(source)
     xPlayer.removeInventoryItem('cartonmojitos', 1)
     xPlayer.addInventoryItem('mojitos', 50)
end)
--
ESX.RegisterUsableItem('cartonrhum', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	TriggerClientEvent('carton:cartonrhum', source)
end)
RegisterServerEvent("carton:cartonrhumopen")
AddEventHandler("carton:cartonrhumopen", function()
	local _source = source
    local xPlayer = ESX.GetPlayerFromId(source)
     xPlayer.removeInventoryItem('cartonrhum', 1)
     xPlayer.addInventoryItem('rhum', 50)
end)
--
ESX.RegisterUsableItem('cartonvodka', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	TriggerClientEvent('carton:cartonvodka', source)
end)
RegisterServerEvent("carton:cartonvodkaopen")
AddEventHandler("carton:cartonvodkaopen", function()
	local _source = source
     local xPlayer        = ESX.GetPlayerFromId(source)
     xPlayer.removeInventoryItem('cartonvodka', 1)
     xPlayer.addInventoryItem('vodka', 50)
end)
--
ESX.RegisterUsableItem('cartontquilafrappee', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	TriggerClientEvent('carton:cartontquilafrappee', source)
end)
RegisterServerEvent("carton:cartontquilafrappeeopen")
AddEventHandler("carton:cartontquilafrappeeopen", function()
	local _source = source
     local xPlayer        = ESX.GetPlayerFromId(source)
     xPlayer.removeInventoryItem('cartontquilafrappee', 1)
     xPlayer.addInventoryItem('tquilafrappee', 50)
end)








ESX.RegisterUsableItem('paquetcigarett', function(source)
    
	local xPlayer = ESX.GetPlayerFromId(source)

	
	xPlayer.removeInventoryItem('paquetcigarett', 1)
	xPlayer.addInventoryItem('cigarett', 20)

	TriggerClientEvent('esx:showNotification', source, ('Vous avez ouvert votre ~g~Paquet de cigarette'))

end)


function IsInVehicle()
	local ply = GetPlayerPed(-1)
	if IsPedSittingInAnyVehicle(ply) then
		return true
	else
		return false
	end
end


ESX.RegisterUsableItem('cigarett', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	local lighter = xPlayer.getInventoryItem('lighter')
	

	
		if lighter.count > 0 then
			xPlayer.removeInventoryItem('cigarett', 1)
			TriggerClientEvent('esx_cigarett:startSmoke', source)
		else
			TriggerClientEvent('esx:showNotification', source, ('~r~Vous n\'avez pas de briquet'))
		end
		
end)

TriggerEvent('es:addGroupCommand', 'heal', 'superadmin', function(source, args, user)
	-- heal another player - don't heal source
	if args[1] then
		local playerId = tonumber(args[1])

		-- is the argument a number?
		if playerId then
			-- is the number a valid player?
			if GetPlayerName(playerId) then
				print(('esx_basicneeds: %s healed %s'):format(GetPlayerIdentifier(source, 0), GetPlayerIdentifier(playerId, 0)))
				TriggerClientEvent('esx_basicneeds:healPlayer', playerId)
				TriggerClientEvent('chat:addMessage', source, { args = { '^5HEAL', 'Vous avez été heal.' } })
			else
				TriggerClientEvent('chat:addMessage', source, { args = { '^1SYSTEM', 'Joueur non connecté.' } })
			end
		else
			TriggerClientEvent('chat:addMessage', source, { args = { '^1SYSTEM', 'Invalid ID.' } })
		end
	else
		print(('esx_basicneeds: %s healed self'):format(GetPlayerIdentifier(source, 0)))
		TriggerClientEvent('esx_basicneeds:healPlayer', source)
	end
end, function(source, args, user)
	TriggerClientEvent('chat:addMessage', source, { args = { '^1SYSTEM', 'Insufficient Permissions.' } })
end, {help = 'Heal a player, or yourself - restores thirst, hunger and health.', params = {{name = 'playerId', help = '(optional) player id'}}})



